@startuml

' я не умею настолько заранее продумывать классы
' и не понимаю, зачем это делать in the first place.
' разработчики сами способны спроектировать отдельный компонент

Bob -> Alice: Hello

@enduml