@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(operator, "Оператор", "Мониторинг алертов и уведомлений")

System(agro_mvp, "АгроТех MVP", "Новая система мониторинга")
System(current_system, "АгроТех Х", "Существующая система")
System_Ext(cam_vendor, "Камеры видеонаблюдения")
System_Ext(sms_gateway, "SMS-шлюз", "Уведомления при отсутствии интернета")
System_Ext(feeding_system, "Система кормления", "Передает команды")
System_Ext(edge_agent, "Edge-Агент", "Прокси RTSP + кэш")

Rel(cam_vendor, edge_agent, "RTSP-поток")
Rel(edge_agent, agro_mvp, "Проксирование видео / кэш")
Rel(operator, agro_mvp, "Использует?")
Rel(agro_mvp, feeding_system, "Передает команды")
Rel(agro_mvp, sms_gateway, "SMS-оповещения")
Rel(agro_mvp, current_system, "Передаёт RTSP-ссылку в AI-кластер")
Rel(sms_gateway, operator, "SMS-оповещения")
@enduml